const data = [
    {
        productName: "Men Printed Hooded Neck Blue",
        productImgs: ["/images/mentshirt1.jpeg","img2"],
        productPrice: "349",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "tshirts",
        productColor: "blue"
    },
    {
        productName: "Men Printed Hooded Neck Red T-Shirt",
        productImgs: ["/images/mentshirt2.webp","img2"],
        productPrice: "299",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "tshirts",
        productColor: "red"
    },
    {
        productName: "Men Full Sleeve Solid Hooded Sweatshirt",
        productImgs: ["/images/mensweat1.webp","img2"],
        productPrice: "549",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "sweatShirts",
        productColor: "black"
    },
    {
        productName: "Men Full Sleeve Printed Hooded Sweatshirt",
        productImgs: ["/images/mensweat2.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "sweatShirts",
        productColor: "green"
    },
    {
        productName: "Men Slim Fit Solid Spread Collar Formal Shirt",
        productImgs: ["/images/menformal1.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "formalShirts",
        productColor: "white"
    },
    {
        productName: "Men Regular Fit Solid Button Down Collar Formal Shirt",
        productImgs: ["/images/menformal2.webp","img2"],
        productPrice: "379",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "formalShirts",
        productColor: "black"
    },
    {
        productName: "Men Slim Mid Rise Blue Jeans",
        productImgs: ["/images/menjeans1.webp","img2"],
        productPrice: "699",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensJeans",
        productColor: "blue"
    },
    {
        productName: "Men Slim Mid Rise Black Jeans",
        productImgs: ["/images/menjeans2.webp","img2"],
        productPrice: "699",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensJeans",
        productColor: "black"
    },
    {
        productName: "Men Regular Fit Blue Pure Cotton Trousers",
        productImgs: ["/images/mentrousers1.webp","img2"],
        productPrice: "604",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensTrousers",
        productColor: "green"
    },
    {
        productName: "Men Regular Fit White Viscose Rayon Trousers",
        productImgs: ["/images/mentrousers2.webp","img2"],
        productPrice: "499",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensTrousers",
        productColor: "white"
    },
    {
        productName: "Solid Men Black Sports Shorts",
        productImgs: ["/images/menshort1.webp","img2"],
        productPrice: "199",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensShorts",
        productColor: "black"
    },
    {
        productName: "Solid Men Green Chino Shorts",
        productImgs: ["/images/menshorts2.webp","img2"],
        productPrice: "574",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensShorts",
        productColor: "green"
    },
    {
        productName: "Modern Trendy Sneakers boot Sneakers Sneakers For Men  (White)",
        productImgs: ["/images/mencasualshoue1.webp","img2"],
        productPrice: "549",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensCasualShoues",
        productColor: "white"
    },
    {
        productName: "Lightweight Pack Of 1 Trendy Sneakers Sneakers For Men  (Black)",
        productImgs: ["/images/mencasualshoues2.webp","img2"],
        productPrice: "259",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensCasualShoues",
        productColor: "black"
    },
    {
        productName: "MIKE (N) Running Shoes For Men  (Blue)",
        productImgs: ["/images/mensportshoues1.webp","img2"],
        productPrice: "1199",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensSportShoues",
        productColor: "blue"
    },
    {
        productName: "Daily Use Running Shoes For Men  (Black)",
        productImgs: ["/images/mensportshoues2.webp","img2"],
        productPrice: "359",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensSportShoues",
        productColor: "black"
    },
    {
        productName: "Synthetic Leather For Men  (Black)",
        productImgs: ["/images/menformalshou1.webp","img2"],
        productPrice: "479",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensFormalShoues",
        productColor: "black"
    },
    {
        productName: "Synthetic Leather Daily Use For Men",
        productImgs: ["/images/menformalshoes2.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensFormalShoues",
        productColor: "brown"
    },
    {
        productName: "Women Printed Cotton Blend Anarkali Kurta With Attached Dupatta  (Red)",
        productImgs: ["/images/womenkurta1.webp","img2"],
        productPrice: "429",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "kurtas",
        productColor: "red"
    },
    {
        productName: "Women Embroidered Viscose Rayon A-line Kurta  (Yellow)",
        productImgs: ["/images/womenkurtas2.webp","img2"],
        productPrice: "479",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "kurtas",
        productColor: "yellow"
    },
    {
        productName: "Self Design Bollywood Net Saree  (Green)",
        productImgs: ["/images/womensarees1.webp","img2"],
        productPrice: "319",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "sarees",
        productColor: "green"
    },
    {
        productName: "Self Design Bollywood Net Saree  (Blue)",
        productImgs: ["/images/womensarees2.webp","img2"],
        productPrice: "319",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "sarees",
        productColor: "blue"
    },
    {
        productName: "Floral Print Semi Stitched Lehenga Choli  (Green)",
        productImgs: ["/images/womenlehenga1.webp","img2"],
        productPrice: "499",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "lehenga",
        productColor: "green"
    },
    {
        productName: "Checkered Semi Stitched Lehenga Choli  (Yellow)",
        productImgs: ["/images/womenlehenga2.webp","img2"],
        productPrice: "279",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "lehenga",
        productColor: "yellow"
    },
    {
        productName: "Plum Eye-Swear-by Eye've Got You Trio  (2 Items in the set)",
        productImgs: ["/images/womenmakeup1.webp","img2"],
        productPrice: "996",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "makeup",
        productColor: "purple"
    },
    {
        productName: "TYA 24 eyeshadow ,1sponge puff (combo kit) (3 Items in the set)",
        productImgs: ["/images/womenmakeup2.webp","img2"],
        productPrice: "340",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "makeup",
        productColor: "pink"
    },
    {
        productName: "Rf Skincare, Australia 15% VITAMIN C Face Serum for Anti- Ageing",
        productImgs: ["/images/womenskincare1.webp","img2"],
        productPrice: "843",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "skinCare",
        productColor: "red"
    },
    {
        productName: "Enhance Skincare Vitamin C Face Scrub with Turmeric & Honey Scrub  (200 ml)",
        productImgs: ["/images/womenskincare2.webp","img2"],
        productPrice: "375",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "skinCare",
        productColor: "white"
    },
    {
        productName: "Just Herbs Ayurvedic Herb Enriched Burnt Red Matte Lipstick for Lip Moisturizing",
        productImgs: ["/images/womenlipstik1.webp","img2"],
        productPrice: "371",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "lipstiks",
        productColor: "red"
    },
    {
        productName: "HUDA CRUSH Insta beauty Non Transfer Liquid Matte Lipsticks Set of 12",
        productImgs: ["/images/womenlipstik2.webp","img2"],
        productPrice: "331",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "lipstiks",
        productColor: "pink"
    }
]

export default data