const data = [
    {
        productName: "Men Printed Hooded Neck Blue",
        productImgs: ["/images/mentshirt1.jpeg","img2"],
        productPrice: "349",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "tshirts",
        productColor: "blue"
    },
    {
        productName: "multi-varient product",
        productImgs: ["/images/mentshirt1.jpeg","img2"],
        productPrice: "349",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "tshirts",
        productColor: "blue",
        varients:[
            {
                size:'S',
                colors:[{color:'red',price:'200'},{color:'black',price:'300'}]
            },
            {
                size:'M',
                colors:[{color:'green',price:'400'},{color:'blue',price:'500'}]
            }
        ]
    },
    {
        productName: "Men Printed Hooded Neck Red T-Shirt",
        productImgs: ["/images/mentshirt2.webp","img2"],
        productPrice: "299",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "tshirts",
        productColor: "red"
    },
    {
        productName: "Men Full Sleeve Solid Hooded Sweatshirt",
        productImgs: ["/images/mensweat1.webp","img2"],
        productPrice: "549",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "sweatShirts",
        productColor: "black"
    },
    {
        productName: "Men Full Sleeve Printed Hooded Sweatshirt",
        productImgs: ["/images/mensweat2.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "sweatShirts",
        productColor: "green"
    },
    {
        productName: "Men Slim Fit Solid Spread Collar Formal Shirt",
        productImgs: ["/images/menformal1.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "formalShirts",
        productColor: "white"
    },
    {
        productName: "Men Regular Fit Solid Button Down Collar Formal Shirt",
        productImgs: ["/images/menformal2.webp","img2"],
        productPrice: "379",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "topWear",
        productChildCat: "formalShirts",
        productColor: "black"
    },
    {
        productName: "Men Slim Mid Rise Blue Jeans",
        productImgs: ["/images/menjeans1.webp","img2"],
        productPrice: "699",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensJeans",
        productColor: "blue"
    },
    {
        productName: "Men Slim Mid Rise Black Jeans",
        productImgs: ["/images/menjeans2.webp","img2"],
        productPrice: "699",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensJeans",
        productColor: "black"
    },
    {
        productName: "Men Regular Fit Blue Pure Cotton Trousers",
        productImgs: ["/images/mentrousers1.webp","img2"],
        productPrice: "604",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensTrousers",
        productColor: "green"
    },
    {
        productName: "Men Regular Fit White Viscose Rayon Trousers",
        productImgs: ["/images/mentrousers2.webp","img2"],
        productPrice: "499",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensTrousers",
        productColor: "white"
    },
    {
        productName: "Solid Men Black Sports Shorts",
        productImgs: ["/images/menshort1.webp","img2"],
        productPrice: "199",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensShorts",
        productColor: "black"
    },
    {
        productName: "Solid Men Green Chino Shorts",
        productImgs: ["/images/menshorts2.webp","img2"],
        productPrice: "574",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "bottomWear",
        productChildCat: "mensShorts",
        productColor: "green"
    },
    {
        productName: "Modern Trendy Sneakers boot Sneakers Sneakers For Men  (White)",
        productImgs: ["/images/mencasualshoue1.webp","img2"],
        productPrice: "549",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensCasualShoues",
        productColor: "white"
    },
    {
        productName: "Lightweight Pack Of 1 Trendy Sneakers Sneakers For Men  (Black)",
        productImgs: ["/images/mencasualshoues2.webp","img2"],
        productPrice: "259",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensCasualShoues",
        productColor: "black"
    },
    {
        productName: "MIKE (N) Running Shoes For Men  (Blue)",
        productImgs: ["/images/mensportshoues1.webp","img2"],
        productPrice: "999",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensSportShoues",
        productColor: "blue"
    },
    {
        productName: "Daily Use Running Shoes For Men  (Black)",
        productImgs: ["/images/mensportshoues2.webp","img2"],
        productPrice: "359",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensSportShoues",
        productColor: "black"
    },
    {
        productName: "Synthetic Leather For Men  (Black)",
        productImgs: ["/images/menformalshou1.webp","img2"],
        productPrice: "479",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensFormalShoues",
        productColor: "black"
    },
    {
        productName: "Synthetic Leather Daily Use For Men",
        productImgs: ["/images/menformalshoes2.webp","img2"],
        productPrice: "399",
        productDesc: "desc",
        productQty: "20",
        productCat: "men",
        productSubCat: "footWear",
        productChildCat: "mensFormalShoues",
        productColor: "brown"
    },
    {
        productName: "Women Printed Cotton Blend Anarkali Kurta With Attached Dupatta  (Red)",
        productImgs: ["/images/womenkurta1.webp","img2"],
        productPrice: "429",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "kurtas",
        productColor: "red"
    },
    {
        productName: "Women Embroidered Viscose Rayon A-line Kurta  (Yellow)",
        productImgs: ["/images/womenkurtas2.webp","img2"],
        productPrice: "479",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "kurtas",
        productColor: "yellow"
    },
    {
        productName: "Self Design Bollywood Net Saree  (Green)",
        productImgs: ["/images/womensarees1.webp","img2"],
        productPrice: "319",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "sarees",
        productColor: "green"
    },
    {
        productName: "Self Design Bollywood Net Saree  (Blue)",
        productImgs: ["/images/womensarees2.webp","img2"],
        productPrice: "319",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "sarees",
        productColor: "blue"
    },
    {
        productName: "Floral Print Semi Stitched Lehenga Choli  (Green)",
        productImgs: ["/images/womenlehenga1.webp","img2"],
        productPrice: "499",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "lehenga",
        productColor: "green"
    },
    {
        productName: "Checkered Semi Stitched Lehenga Choli  (Yellow)",
        productImgs: ["/images/womenlehenga2.webp","img2"],
        productPrice: "279",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "indianWear",
        productChildCat: "lehenga",
        productColor: "yellow"
    },
    {
        productName: "Plum Eye-Swear-by Eye've Got You Trio  (2 Items in the set)",
        productImgs: ["/images/womenmakeup1.webp","img2"],
        productPrice: "996",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "makeup",
        productColor: "purple"
    },
    {
        productName: "TYA 24 eyeshadow ,1sponge puff (combo kit) (3 Items in the set)",
        productImgs: ["/images/womenmakeup2.webp","img2"],
        productPrice: "340",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "makeup",
        productColor: "pink"
    },
    {
        productName: "Rf Skincare, Australia 15% VITAMIN C Face Serum for Anti- Ageing",
        productImgs: ["/images/womenskincare1.webp","img2"],
        productPrice: "843",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "skinCare",
        productColor: "red"
    },
    {
        productName: "Enhance Skincare Vitamin C Face Scrub with Turmeric & Honey Scrub  (200 ml)",
        productImgs: ["/images/womenskincare2.webp","img2"],
        productPrice: "375",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "skinCare",
        productColor: "white"
    },
    {
        productName: "Just Herbs Ayurvedic Herb Enriched Burnt Red Matte Lipstick for Lip Moisturizing",
        productImgs: ["/images/womenlipstik1.webp","img2"],
        productPrice: "371",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "lipstiks",
        productColor: "red"
    },
    {
        productName: "HUDA CRUSH Insta beauty Non Transfer Liquid Matte Lipsticks Set of 12",
        productImgs: ["/images/womenlipstik2.webp","img2"],
        productPrice: "331",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "beauty",
        productChildCat: "lipstiks",
        productColor: "pink"
    },
    {
        productName: "Women Black Heels Sandal",
        productImgs: ["/images/womenheels1.webp","img2"],
        productPrice: "299",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenHeels",
        productColor: "black"
    },
    {
        productName: "Women Blue Heels Sandal",
        productImgs: ["/images/womenhells2.webp","img2"],
        productPrice: "889",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenHeels",
        productColor: "blue"
    },
    {
        productName: "Cute sports shoes for women | Running shoes for girls stylish latest design new fashion",
        productImgs: ["/images/womensportshoe1.webp","img2"],
        productPrice: "486",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenSports",
        productColor: "pink"
    },
    {
        productName: "NOOR PLUS Running Shoes For Women  (Black)",
        productImgs: ["/images/womensportshoe2.webp","img2"],
        productPrice: "599",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenSports",
        productColor: "black"
    },
    {
        productName: "Women Green Flats Sandal",
        productImgs: ["/images/womenflats1.webp","img2"],
        productPrice: "295",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenFlats",
        productColor: "green"
    },
    {
        productName: "Women Pink Flats Sandal",
        productImgs: ["/images/womenflats2.webp","img2"],
        productPrice: "328",
        productDesc: "desc",
        productQty: "20",
        productCat: "women",
        productSubCat: "womenFootWear",
        productChildCat: "womenFlats",
        productColor: "green"
    },
    {
        productName: "Boys Typography Cotton Blend T Shirt  (Yellow, Pack of 1)",
        productImgs: ["/images/kidstshirt1.webp","img2"],
        productPrice: "349",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysTshirts",
        productColor: "yellow"
    },
    {
        productName: "Boys Typography Cotton Blend T Shirt  (White, Pack of 1)",
        productImgs: ["/images/kidstshirt2.webp","img2"],
        productPrice: "332",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysTshirts",
        productColor: "white"
    },
    {
        productName: "Boys Regular Fit Floral Print Casual Shirt",
        productImgs: ["/images/kidsshirt1.webp","img2"],
        productPrice: "379",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysShirts",
        productColor: "green"
    },
    {
        productName: "Boys Regular Fit Solid Casual Shirt",
        productImgs: ["/images/kidsshirts2.webp","img2"],
        productPrice: "471",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysShirts",
        productColor: "red"
    },
    {
        productName: "Short For Boys Casual Printed, Solid Pure Cotton  (Multicolor, Pack of 5)",
        productImgs: ["/images/boysshort1.webp","img2"],
        productPrice: "244",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysShorts",
        productColor: "mix"
    },
    {
        productName: "Short For Boys Casual Printed Cotton Blend  (Multicolor, Pack of 1)",
        productImgs: ["/images/boysshorts2.webp","img2"],
        productPrice: "322",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "boysClothing",
        productChildCat: "boysShorts",
        productColor: "black"
    },
    {
        productName: "Girls Midi/Knee Length Party Dress  (Red, Sleeveless)",
        productImgs: ["/images/girlsdress1.webp","img2"],
        productPrice: "176",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsDresses",
        productColor: "red"
    },
    {
        productName: "Girls Below Knee Festive/Wedding Dress  (Pink, 3/4 Sleeve)",
        productImgs: ["/images/girlsdress2.webp","img2"],
        productPrice: "266",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsDresses",
        productColor: "pink"
    },
    {
        productName: "Girls Casual Cotton Rayon Blend Peplum Top  (Maroon, Pack of 1)",
        productImgs: ["/images/girlstop1.webp","img2"],
        productPrice: "322",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsTops",
        productColor: "red"
    },
    {
        productName: "Girls Lycra Blend Fashion Sleeve Top  (White, Pack of 1)",
        productImgs: ["/images/girlstop2.webp","img2"],
        productPrice: "279",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsTops",
        productColor: "white"
    },
    {
        productName: "Girls Printed Pure Cotton T Shirt  (Pink, Pack of 1)",
        productImgs: ["/images/girltshirt1.webp","img2"],
        productPrice: "101",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsTshirts",
        productColor: "pink"
    },
    {
        productName: "Girls Printed Cotton Blend T Shirt  (Black, Pack of 1)",
        productImgs: ["/images/girltshirt2.webp","img2"],
        productPrice: "149",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "girlsClothing",
        productChildCat: "girlsTshirts",
        productColor: "black"
    },
    {
        productName: "Frantic Kids Soft Animal Cartoon Velvet Plush School Bag",
        productImgs: ["/images/kidsbags1.webp","img2"],
        productPrice: "289",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "bags",
        productColor: "pink"
    },
    {
        productName: "Medium 30 L Laptop Backpack Medium 30 L",
        productImgs: ["/images/kidsbags2.webp","img2"],
        productPrice: "299",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "bags",
        productColor: "black"
    },
    {
        productName: "KJR_32 KJR_32 Analog Watch - For Men",
        productImgs: ["/images/kidswatches1.webp","img2"],
        productPrice: "224",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "watches",
        productColor: "black"
    },
    {
        productName: "Digital Spiderman Wonderful Projector Watch for Kids,",
        productImgs: ["/images/kidswatches2.webp","img2"],
        productPrice: "269",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "watches",
        productColor: "red"
    },
    {
        productName: "KAKU FANCY DRESSES Kids Golden Party Hat  (Golden, Pack of 1)",
        productImgs: ["/images/hats1.webp","img2"],
        productPrice: "299",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "hats",
        productColor: "yellow"
    },
    {
        productName: "Top Trick Fedora Hat  (Red, Pack of 1)",
        productImgs: ["/images/hats2.webp","img2"],
        productPrice: "224",
        productDesc: "desc",
        productQty: "20",
        productCat: "kids",
        productSubCat: "accessories",
        productChildCat: "hats",
        productColor: "red"
    }
]

export default data